[package]
name = "omni-orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json", "uuid"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
raft = "0.7"
async-trait = "0.1"
reqwest = { version = "0.11", features = ["json"] }
log = "0.4"
env_logger = "0.9"
thiserror = "1.0"
parking_lot = "0.12"
chrono = "0.4.39"
futures = "0.3.31"
colored = "2.2.0"
anyhow = "1.0.95"
lazy_static = "1.5.0"


[profile.dev]
codegen-units = 32
incremental = true
debug-assertions = false
overflow-checks = false
opt-level = 0
lto = "thin"
